default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock 

development:
  <<: *default
  database: review_development
production:
  <<: *default
  database: review_development
